# Generated by Django 6.0.1 on 2026-01-28 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_drinks"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrinksCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="drinks",
            name="category_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.drinkscategory",
            ),
        ),
    ]
